# Generated by hand on 2026-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_cedula_rif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula/RIF del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('pago_movil', 'Pago Móvil'), ('punto_venta', 'Punto de Venta')], default='efectivo', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Tasa de Cambio'),
        ),
    ]
