# Generated by Django 4.2.30 on 2026-06-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_venta_adiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Otros', max_length=100, verbose_name='Categoría'),
        ),
    ]
