# Generated by Django 4.2.30 on 2026-06-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='igtf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto IGTF (3%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto IVA (16%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_restante',
            field=models.CharField(blank=True, choices=[('pago_movil', 'Pago Móvil'), ('punto_venta', 'Punto de Venta')], max_length=50, null=True, verbose_name='Método de Pago Restante (Bs)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_efectivo_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto pagado en Efectivo USD'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_electronico_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto pagado en Bs electrónico'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('pago_movil', 'Pago Móvil'), ('punto_venta', 'Punto de Venta'), ('mixto', 'Mixto (USD + Bs)')], default='efectivo', max_length=50, verbose_name='Método de Pago'),
        ),
    ]
