# Generated by Django 4.2.30 on 2026-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_venta_igtf_venta_iva_venta_metodo_pago_restante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha de Cierre')),
                ('monto_acumulado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Acumulado')),
                ('productos_vendidos_count', models.IntegerField(verbose_name='Cantidad Total de Unidades')),
                ('tasa_cambio', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Tasa de Cambio')),
                ('efectivo_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Efectivo USD')),
                ('pago_movil_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pago Móvil USD')),
                ('punto_venta_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Punto de Venta USD')),
                ('sincronizado_n8n', models.BooleanField(default=False, verbose_name='Sincronizado con n8n')),
                ('mensaje_n8n', models.TextField(blank=True, null=True, verbose_name='Mensaje de n8n')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Costo Unitario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Costo'),
        ),
    ]
