# Generated by Django 4.2.30 on 2026-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_cierrecaja_detalleventa_precio_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Descuento (USD)'),
        ),
    ]
