# Generated by Django 4.2.30 on 2026-07-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada'), ('con_cambios', 'Con Cambios')], default='completada', max_length=20, verbose_name='Estado de la Venta'),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('tipo', models.CharField(choices=[('anulacion', 'Anulación'), ('cambio', 'Cambio')], default='anulacion', max_length=20, verbose_name='Tipo de Operación')),
                ('monto_saldo_favor_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Saldo a Favor (USD)')),
                ('monto_saldo_favor_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Saldo a Favor (Bs.)')),
                ('diferencia_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Diferencia Monetaria (USD)')),
                ('metodo_diferencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Diferencia')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventario.venta', verbose_name='Venta Original')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Devuelta')),
                ('precio_original_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Original (USD)')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.devolucion', verbose_name='Devolución')),
                ('producto_devuelto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_devueltos', to='inventario.producto', verbose_name='Producto Devuelto')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
        migrations.CreateModel(
            name='DetalleCambioNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Entregada')),
                ('precio_venta_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta Cobrado (USD)')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuevos_items', to='inventario.devolucion', verbose_name='Devolución')),
                ('producto_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_nuevos', to='inventario.producto', verbose_name='Producto Nuevo Entregado')),
            ],
            options={
                'verbose_name': 'Detalle de Cambio Nuevo',
                'verbose_name_plural': 'Detalles de Cambio Nuevo',
            },
        ),
    ]
